// components/Elimore.vue
<script setup>
import {ref, computed} from "vue";

const props = defineProps({
  text: {type: String, required: true},
  maxLength: {type: Number, default: 130},
  moreText: {type: String, default: "..."}
});

const expanded = ref(false);

const preview = computed(() => props.text.length > props.maxLength ? props.text.slice(0, props.maxLength) : props.text);

const needsEllipsis = computed(() => props.text.length > props.maxLength);
</script>

<template>
  <div class="elimore">
    <span v-if="!needsEllipsis">{{ text }}</span>
    <template v-else>
      <span v-if="!expanded" class="elimore_preview">{{ preview }}</span>
      <a v-if="!expanded" class="elimore_show" @click="expanded = true">{{ moreText }}</a>
      <span v-else class="elimore_trim">{{ text }}</span>
    </template>
  </div>
</template>

<style scoped>
.elimore_show {
  cursor: pointer;
}
</style>

// components/Elimore.jsx
import {useState} from "react";

function Elimore({text, maxLength = 130, moreText = "..."}) {
    const [expanded, setExpanded] = useState(false);

    if (!text || text.length <= maxLength) {
        return <span>{text}</span>;
    }

    const preview = text.slice(0, maxLength);

    return (
        <div className="elimore">
            {!expanded ? (
                <>
                    <span className="elimore_preview">{preview}</span>
                    <a className="elimore_show" onClick={() => setExpanded(true)}
                       style={{cursor: "pointer"}}>{moreText}</a>
                </>
            ) : (
                <span className="elimore_trim">{text}</span>
            )}
        </div>
    );
}

export default Elimore;
